### ISSUE TITLE
The UI is buggy

### ISSUE THREAD

**Issue by failable** [moxin-org/moly#128]
<img width="1552" alt="image" src="https://github.com/moxin-org/moxin/assets/5475262/ea44a292-7a7a-41dc-939a-6f49564538e0">

- System: `macOS 14.5 (23F79)`

**Comment by joulei** [comment]
Hi @failable thanks for reporting, how are you running the application? 
If you're doing so through something like `cargo run..`, are you getting any kind of warnings or errors in the terminal?

**Comment by failable** [comment]
I'm using `cargo run` but noting is printed to the terminal. The issue happens when I start to scroll the window.

**Comment by joulei** [comment]
@failable thanks for confirming. I'm having trouble replicating this just with the same macOS version, some questions:
- is this happening on an intel or apple chip?
- what rust version are you on?
- by any chance, is this happening in an external monitor only? (if so share details)
- have you tried other Makepad apps and had similar issues?
(I'm assuming you're running with the latest in `main`)

**Comment by failable** [comment]
Hello, 

> is your system running on an intel or apple chip?

Intel.

> which rust version are you on?

`rustc 1.79.0 (129f3b996 2024-06-10)`.

> by any chance, is this happening in an external monitor only? (if so share details)

I don't have external monitor.

> have you tried other Makepad apps and had similar issues?

Not yet.

**Comment by joulei** [comment]
Sorry for the late follow-up, we haven't managed to replicate this on macOS at all.
It's been a while now and there have been a lot of changes to Makepad, including platform specific code, `PortalList` cahnges (the widget used for that list of models), etc.. Hopefully this issue is no longer happening.
If the same issue or similar issues arise, please open let us know!
